### ISSUE TITLE
USB Pins not defined on Core 4.0.10

### ISSUE THREAD

**Issue by MoveElectricMobility** [arduino/ArduinoCore-mbed#786]
After update from 4.0.8 to 4.0.10 it has broken the USB library for the Giga. The following error dump during compilation is generated:

`In file included from c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.cpp:33:0:
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:137:2: error: #error "USB power pin is not configured !"
 #error "USB power pin is not configured !"
  ^~~~~
In file included from c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.cpp:33:0:
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:336:2: error: #error "USB pins are not configured !"
 #error "USB pins are not configured !"
  ^~~~~
In file included from c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.cpp:33:0:
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h: In function 'void usb_vbus(uint8_t)':
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:145:40: error: 'USB_POWER_OFF' was not declared in this scope
             gpio_write(&gpio_powerpin, USB_POWER_OFF);
                                        ^~~~~~~~~~~~~
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:145:40: note: suggested alternative: 'USB_TYPE_OK'
             gpio_write(&gpio_powerpin, USB_POWER_OFF);
                                        ^~~~~~~~~~~~~
                                        USB_TYPE_OK
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:147:40: error: 'USB_POWER_ON' was not declared in this scope
             gpio_write(&gpio_powerpin, USB_POWER_ON);
                                        ^~~~~~~~~~~~
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:147:40: note: suggested alternative: 'USB_TYPE_OK'
             gpio_write(&gpio_powerpin, USB_POWER_ON);
                                        ^~~~~~~~~~~~
                                        USB_TYPE_OK
In file included from c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.cpp:33:0:
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h: In constructor 'USBHALHost::USBHALHost()':
c:\Users\chris\OneDrive\Documents\Arduino\libraries\Arduino_USBHostMbed5\src\targets\TARGET_STM\USBHALHost_STM.h:342:5: error: 'USB_POWERPIN_CONFIG' was not declared in this scope
     USB_POWERPIN_CONFIG;`
